config/routes.rb
Rails.application.routes.draw do
  resources :vehicles
  root 'vehicles#index'
  resources :drivers
  root 'drivers#index'
  resources :vehicles_comments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/driver.rb
class Driver < ApplicationRecord
  has_one :vehicles
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  attr_accessor :driver_name
  has_one :drivers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  
  def index
    @drivers = Driver.order(created_at: :desc)
  end

  def show
    set_driver
    @driver = Driver.find(params[:id])
  end

  def new
    @driver = Driver.new
  end

  def edit
    set_driver
  end

  def create
    @driver = Driver.new(driver_params)

    respond_to do |format|
      if @driver.save
        format.html { redirect_to @driver, notice: 'driver was successfully created.' }
        format.json { render :show, status: :created, location: @driver }
      else
        format.html { render :new }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    set_driver
    respond_to do |format|
      if @driver.update(driver_params)
        format.html { redirect_to @driver, notice: 'driver was successfully updated.' }
        format.json { render :show, status: :ok, location: @driver }
      else
        format.html { render :edit }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    set_driver
    @driver.destroy
    respond_to do |format|
      format.html { redirect_to drivers_url, notice: 'driver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_driver
      @driver = Driver.find(params[:id])
    end


    def driver_params
      params.require(:driver).permit(:driver_name, :driver_surname, :driver_birthday, :TC_NO, :driver_tel, :driver_adress,:drivers_comments)
    end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController

  def index
    @vehicles = Vehicle.order(created_at: :desc)
  end

  def show
    set_vehicle
    @vehicle = Vehicle.find(params[:id])
  end

  def new
    @vehicle = Vehicle.new
  end

  def edit
    set_vehicle
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    set_vehicle
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    set_vehicle
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end


    def vehicle_params
      params.require(:vehicle).permit(:name, :code, :vehicle_class, :brand, :model, :model_year, :fuel_capacity, :fuel_type, :status, :purchase_date,:driver_name,:vehicles_comments)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
  def available_drivers
    Driver.all.order(driver_name: :asc)
  end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/drivers/_form.html.erb
<%= simple_form_for @driver, html: {class: 'horizontal-form'}, validate: true do |f| %>
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <%= f.input :driver_name %>
    </div>
    <div class="col-md-4">
      <%= f.input :driver_birthday %>
    </div>
    <div class="col-md-4">
      <%= f.input :driver_tel %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <%= f.input :driver_surname %>
    </div>
    <div class="col-md-4">
      <%= f.input :TC_NO %>
    </div>
    <div class="col-md-4">
      <%= f.input :driver_adress %>
    </div> 
  </div> 
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/drivers/edit.html.erb
<h1>Editing Driver</h1>

<%= render 'form', driver: @driver %>

<%= link_to 'Show', @driver %> |
<%= link_to 'Back', drivers_path %>

app/views/drivers/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Drivers</h1>
  <table>
    <thead>
      <tr>
        <th>driver_name</th>
        <th>driver_surname</th>
        <th>driver_birthday</th>
        <th>driver_adress</th>
      </tr>
    </thead>

    <tbody>
      <% @drivers.each do |driver| %>
        <tr>
          <td><%= driver.driver_name %></td>
          <td><%= driver.driver_surname %></td>
          <td><%= driver.driver_birthday %></td>
          <td><%= driver.driver_adress %></td>
          <td><%= link_to 'Show', driver %></td>
          <td><%= link_to 'Edit', edit_driver_path(driver) %></td>
          <td><%= link_to 'Destroy', driver, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<br>
<%= link_to 'New driver', new_driver_path %>

app/views/drivers/new.html.erb
<h1>New Driver</h1>

<%= render 'form', driver: @driver %>

<%= link_to 'Back', drivers_path %>

app/views/drivers/show.html.erb
<%= simple_form_for @driver, html: {class: 'horizontal-form'}, validate: true do |f| %>
  <p id="notice"><%= notice %></p>
  <h4><i class="fa fa-truck fa-3x"></i> <%= @driver.driver_name %></h4>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>driver_namer</th>
        <td><%= @driver.driver_name %></td>
        <th>driver_surname</th>
        <td><%= @driver.driver_surname %></td>
        <th>driver_birthday</th>
        <td><%= @driver.driver_birthday %></td>
      </tr>
      <tr>
        <th>driver_TC_NO</th>
        <td><%= @driver.TC_NO %></td>
        <th>driver_tel</th>
        <td><%= @driver.driver_tel %></td>
        <th>driver_adress</th>
        <td><%= @driver.driver_adress %></td>
      </tr>
    </thead>
  </table>
  <p>
    <%= link_to 'Edit', edit_driver_path(@driver) %> |
    <%= link_to 'Back', drivers_path %>
  </p>
  <h5>Yorumlar</h5>
  <%= f.input :drivers_comments%>
  <div>
    <%= f.submit :save %>
  </div>
<table>
  <thead>
    <tr>
      <th>drivers_comments</th>
    </tr>
  </thead>

  <tbody>
    
      <tr>
        <td><%= @driver.drivers_comments %></td>
      </tr>
  </tbody>
</table>
<% end %>

app/views/layouts/_navbar.html.erb
<ul class="nav">
  <li class="nav-item">
    <%= link_to "Vehicles", vehicles_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "Drivers", drivers_path, class: "nav-link" %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <%= render "layouts/navbar" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/vehicles/_form.html.erb
<%= simple_form_for @vehicle, html: {class: 'horizontal-form'}, validate: true do |f| %>
  <% if vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>
      <ul>
        <% vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class= "container">
      <div class="row">
        <div class="col-md-4">
          <%= f.input :name %>
        </div>
        <div class="col-md-4">
          <%= f.input :vehicle_class %>
        </div>
        <div class="col-md-4">
          <%= f.input :fuel_type %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">
          <%= f.input :brand %>
        </div>
        <div class="col-md-4">
          <%= f.input :model_year %>
        </div>
        <div class="col-md-4">
          <%= f.input :fuel_capacity %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">
          <%= f.input :model %>
        </div>
        <div class="col-md-4">
          <%= f.input :status %>
        </div>
        <div class="col-md-4">
          <%= f.label :purchase_date %>
          <%= f.date_field :purchase_date, class: 'form-control basicDate' %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">
          <%= f.input :code %>
        </div>
        <div class="col-md-4">
          <%= f.input :driver_name, collection: available_drivers %>
        </div>
      </div>  
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
    </div>
    
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehicles</h1>

<table>
  <thead>
    <tr>
      <th>name</th>
      <th>code</th>
      <th>vehicle_class</th>
      <th>brand</th>
      <th>model</th>
      <th>model_year</th>
      <th>fuel_capacity</th>
      <th>fuel_type</th>
      <th>status</th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.name %></td>
        <td><%= vehicle.code %></td>
        <td><%= vehicle.vehicle_class %></td>
        <td><%= vehicle.brand %></td>
        <td><%= vehicle.model %></td>
        <td><%= vehicle.model_year %></td>
        <td><%= vehicle.fuel_capacity %></td>
        <td><%= vehicle.fuel_type %></td>
        <td><%= vehicle.status %></td>
        <td><%= link_to 'Show', vehicle %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle', new_vehicle_path %>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<%= simple_form_for @vehicle, html: {class: 'horizontal-form'}, validate: true do |f| %>
<p id="notice"><%= notice %></p>
<h4><i class="fa fa-truck fa-3x"></i> <%= @vehicle.code %></h4>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>vehicle_class</th>
      <td><%= @vehicle.vehicle_class %></td>
      <th>brand</th>
      <td><%= @vehicle.brand %></td>
      <th>model</th>
      <td><%= @vehicle.model %></td>
    </tr>
    <tr>
      <th>model_year</th>
      <td><%= @vehicle.model_year %></td>
      <th>fuel_capacity</th>
      <td><%= @vehicle.fuel_capacity %></td>
      <th>fuel_type</th>
      <td><%= @vehicle.fuel_type %></td>
    </tr>
    <tr>
      <th>status</th>
      <td><%= @vehicle.status %></td>
      <th>purchase_date</th>
      <td><%= @vehicle.purchase_date %></td>
      <th></th>
      <td></td>
    </tr>
  </thead>
</table>
<p>
  <%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
  <%= link_to 'Back', vehicles_path %>
</p>
<h5>Yorumlar</h5>
<%= f.input :vehicles_comments%>
<div>
  <%= f.submit :save %>
</div>
<table>
  <thead>
    <tr>
      <th>vehicles_comments</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @vehicle.vehicles_comments %></td>
      </tr>
  </tbody>
</table>
<p>Vehicle's Driver</p>
<%= @vehicle.driver_name %>
<% end %>